const listpesan = [
    'semangat bang', 
    'semangat ya',
    'semangat terus',
    'bang kapan giveaway?', 
    'bang kapan live lagi?', 
    'bang kapan upload lagi?', 
    'bang kapan buka member',
    'bang kapan buka donasi lagi?',
    'Bang sapa aku dong',
    'Bang aku kangen',
    'Bang aku cinta kamu',
    'Sebut namaku bang',
    'Kak kok streamnya ngelag',
    'kak kaapan aplodddd lagiiiiii',
    'kak aku suka sama seseorang tapi aku bingung cara ngungkapinnya gimana ya kak',
    'Waras ga kak jatuh cinta sama orang yang belum tentu suka sama kita?',
    'Kak aku suka sama orang yang udah punya pacar, gimana ya kak?',
    'Kak cara jadi yutuber gimana ya kak?',
    'Kak aku suka sama orang yang beda agama, gimana ya kak?',
    'Kak opinimu sama penjual esteh di acara gus miftah apa ya',
    'ABSEN BANGGGGG',
    'Kenapa kamu ganteng banget sih bang',
    'Aisbir ganteng banget',
    'Kak kalok ada orang di real life kelakuannya kayak biadap tapi di sosmed sok alim enaknya dibikin bakso apa martabak ya kak',
    'Kak aku suka sama seseorang, tapi aku gasuka idola dia, nanti dia bandingin standar ganteng sama idolanya dongg',
    'kak spill playlist spotifymu',
    'Kak apakah halal menjadikan teman menjadi rendang',
    'Bang spill setup pcmu aku pengen niru hehe',
    'kongrats ya bangg!',
    `Ada jadwal live lagi ga bang?`,
    `Ganti lagu metal bang biar seru`,
    `Kak aku pengen sukses di usia muda, apakah ada saran?`,
    `Kak aku mikir nanti lulus smk ini bingung mau kerja apa kuliah, karena aku ga ada bakat apa apa`,
    `Bang cara deketin wanita yang ku suka gimana ya?`,
    `Bang aku suka salting liat wanita yang kusuka, apa normal ya?`,
    `EDO HOMOK`,
    'Bang Aku mau masuk surga',
    '100 subs daget ya bang',
    `plis bang besok live mukul pc`,
    'Bang kapan main game horror lagi?',
    'Bang, aku suka kontenmu!',
    'Bang, kapan collab sama youtuber lain?',
    'Bang, aku pengen jadi streamer kayak kamu!',
    'Bang, kasih tips biar bisa jago main game dong!',
    'Bang, aku baru putus, semangat dong!',
    'Bang, aku lagi sedih, hibur aku dong!',
    'Bang, kapan face reveal?',
    'Bang, aku ngefans banget sama kamu!',
    'Bang, kapan QnA lagi?',
    'Bang, aku suka banget sama jokes kamu!',
    'Bang, kapan bikin vlog?',
    'Bang, aku suka banget sama editan videomu!',
    'Bang, kapan bikin konten tutorial?',
    'Bang, aku suka banget sama intro videomu!',
    'Bang, kapan bikin konten prank?',
    'Bang, aku suka banget sama outro videomu!',
    'Bang, kapan bikin konten challenge?',
    'Bang, aku suka banget sama thumbnail videomu!',
    'Bang, kapan bikin konten reaction?',
    'Bang, aku suka banget sama musik di videomu!',
    'Bang, kapan bikin konten review?',
    'Bang, aku suka banget sama lighting di videomu!',
    'Bang, kapan bikin konten unboxing?',
    'Bang, aku suka banget sama background di videomu!'
];
module.exports = listpesan